services:
  macromate.webapi:
    image: macromate.webapi
    build:
      context: .
      dockerfile: src/MacroMate.WebApi/Dockerfile
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: macromate
      NAMEDATALEN: 100
