/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Flekt
 * OpenAPI spec version: v1
 */
import { z as zod } from "zod";

export const addFamilyMemberBody = zod.object({
  addedUserDisplayName: zod.string(),
  addedUserEmail: zod.string(),
});

export const authenticateWorkOsUserBody = zod.object({
  code: zod.string(),
  state: zod.string(),
  redirectUri: zod.string(),
});

export const authenticateWorkOsUserResponse = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export const workOsRedirectBody = zod.object({
  returnPath: zod.string(),
  provider: zod.enum([
    "AppleOAuth",
    "GitHubOAuth",
    "GoogleOAuth",
    "MicrosoftOAuth",
  ]),
});

export const workOsRedirectResponse = zod.object({
  redirectUrl: zod.string(),
});
