/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Flekt
 * OpenAPI spec version: v1
 */

export interface MacroMateWebApiFeaturesUsersHandlersAuthenticateUserResult {
  accessToken: string;
  refreshToken: string;
}
