/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Flekt
 * OpenAPI spec version: v1
 */

export interface MacroMateWebApiFeaturesUsersHandlersAuthenticateWorkOsUserRequest {
  code: string;
  state: string;
  redirectUri: string;
}
