/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Flekt
 * OpenAPI spec version: v1
 */
import type { WorkOSProviderType } from "./workOSProviderType";

export interface MacroMateWebApiFeaturesUsersHandlersWorkOsRedirectRequest {
  returnPath: string;
  provider: WorkOSProviderType;
}
