/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Flekt
 * OpenAPI spec version: v1
 */

export type WorkOSProviderType =
  (typeof WorkOSProviderType)[keyof typeof WorkOSProviderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkOSProviderType = {
  AppleOAuth: "AppleOAuth",
  GitHubOAuth: "GitHubOAuth",
  GoogleOAuth: "GoogleOAuth",
  MicrosoftOAuth: "MicrosoftOAuth",
} as const;
